--------------------------------------------------------
--  File created - Monday-December-16-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type TYPE_CUSTOMER_RECORD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "FINAL"."TYPE_CUSTOMER_RECORD" AS OBJECT (
  CUSTOMER_ID CHAR(32 BYTE),
  FIRST_NAME VARCHAR2(20 BYTE),
  LAST_NAME VARCHAR2 (20 BYTE)
)

/
--------------------------------------------------------
--  DDL for Type TYPE_CUSTOMER_RECORD_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "FINAL"."TYPE_CUSTOMER_RECORD_TABLE" 
AS TABLE OF TYPE_CUSTOMER_RECORD;

/
--------------------------------------------------------
--  DDL for Type TYPE_PURCHASE_RECORD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "FINAL"."TYPE_PURCHASE_RECORD" AS OBJECT (
  CREATED DATE,
  FIRST_NAME VARCHAR2(50),
  LAST_NAME VARCHAR2(50),
  DESCRIPTION
  VARCHAR2(100),
  PRICE NUMBER,
  QUANTITY NUMBER,
  TOTAL NUMBER,
  CUMULATIVE NUMBER
);

/
--------------------------------------------------------
--  DDL for Type TYPE_PURCHASE_RECORD_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "FINAL"."TYPE_PURCHASE_RECORD_TABLE" 
AS TABLE OF TYPE_PURCHASE_RECORD;

/
--------------------------------------------------------
--  DDL for Sequence INVOICE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "FINAL"."INVOICE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "FINAL"."CUSTOMERS" 
   (	"CUSTOMER_ID" CHAR(32 CHAR) DEFAULT SYS_GUID(), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"ADDRESS" CHAR(100 CHAR), 
	"CITY" CHAR(30 CHAR), 
	"POSTAL_CODE" CHAR(20 CHAR), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD_HASH" VARCHAR2(256 BYTE), 
	"CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFIED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "FINAL"."PRODUCTS" 
   (	"PRODUCT_ID" CHAR(32 CHAR), 
	"PRODUCT_NAME" VARCHAR2(20 BYTE), 
	"PRODUCT_CODE" VARCHAR2(20 CHAR), 
	"PRODUCT_DESCRIPTION" CHAR(400 CHAR), 
	"PRICE" NUMBER(6,2), 
	"CREATED" TIMESTAMP (6), 
	"MODIFIED" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "FINAL"."SALES" 
   (	"INVOICE_ID" VARCHAR2(50 BYTE), 
	"CUSTOMER_ID" CHAR(32 CHAR), 
	"PRODUCT_ID" CHAR(32 CHAR), 
	"QUANTITY" NUMBER(5,0), 
	"TOTAL_PRICE" NUMBER(10,0), 
	"CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFIED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into FINAL.CUSTOMERS
SET DEFINE OFF;
Insert into FINAL.CUSTOMERS (CUSTOMER_ID,FIRST_NAME,LAST_NAME,ADDRESS,CITY,POSTAL_CODE,EMAIL,PASSWORD_HASH,CREATED,MODIFIED) values ('500C6CFFE19F457286DB90EA41ECD4D5','Sarab','jeet','219 Baker street                                                                                    ','Montréal                      ','H2K 3B7             ','sarab.jeet@example.com','hashed_password1',to_timestamp('16-12-24 3:49:44.759000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('16-12-24 3:49:44.759000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
REM INSERTING into FINAL.PRODUCTS
SET DEFINE OFF;
REM INSERTING into FINAL.SALES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."CUSTOMERS_PK" ON "FINAL"."CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_UK_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."CUSTOMERS_UK_EMAIL" ON "FINAL"."CUSTOMERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."PRODUCTS_PK" ON "FINAL"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_UK_PRODUCT_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."PRODUCTS_UK_PRODUCT_CODE" ON "FINAL"."PRODUCTS" ("PRODUCT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."SALES_PK" ON "FINAL"."SALES" ("INVOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."CUSTOMERS_PK" ON "FINAL"."CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_UK_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."CUSTOMERS_UK_EMAIL" ON "FINAL"."CUSTOMERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."PRODUCTS_PK" ON "FINAL"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_UK_PRODUCT_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."PRODUCTS_UK_PRODUCT_CODE" ON "FINAL"."PRODUCTS" ("PRODUCT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL"."SALES_PK" ON "FINAL"."SALES" ("INVOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CUSTOMER_MODIFIED
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL"."TRIGGER_CUSTOMER_MODIFIED" 
BEFORE UPDATE ON CUSTOMERS 
FOR EACH ROW 
BEGIN
  :NEW.MODIFIED := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL"."TRIGGER_CUSTOMER_MODIFIED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_PRODUCTS_MODIFIED
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL"."TRIGGER_PRODUCTS_MODIFIED" 
BEFORE UPDATE ON PRODUCTS
FOR EACH ROW 
BEGIN
  :NEW.MODIFIED := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL"."TRIGGER_PRODUCTS_MODIFIED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SALES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL"."TRIGGER_SALES" BEFORE
 INSERT ON SALES
 FOR EACH ROW
BEGIN
 :NEW.INVOICE_ID := 'INVOICE' || INVOICE_SEQUENCE.NEXTVAL;
END;
/
ALTER TRIGGER "FINAL"."TRIGGER_SALES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SALES_MODIFIED
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL"."TRIGGER_SALES_MODIFIED" 
BEFORE UPDATE ON SALES
FOR EACH ROW 
BEGIN
  :NEW.MODIFIED := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL"."TRIGGER_SALES_MODIFIED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CUSTOMER_MODIFIED
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL"."TRIGGER_CUSTOMER_MODIFIED" 
BEFORE UPDATE ON CUSTOMERS 
FOR EACH ROW 
BEGIN
  :NEW.MODIFIED := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL"."TRIGGER_CUSTOMER_MODIFIED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_PRODUCTS_MODIFIED
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL"."TRIGGER_PRODUCTS_MODIFIED" 
BEFORE UPDATE ON PRODUCTS
FOR EACH ROW 
BEGIN
  :NEW.MODIFIED := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL"."TRIGGER_PRODUCTS_MODIFIED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SALES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL"."TRIGGER_SALES" BEFORE
 INSERT ON SALES
 FOR EACH ROW
BEGIN
 :NEW.INVOICE_ID := 'INVOICE' || INVOICE_SEQUENCE.NEXTVAL;
END;
/
ALTER TRIGGER "FINAL"."TRIGGER_SALES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SALES_MODIFIED
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL"."TRIGGER_SALES_MODIFIED" 
BEFORE UPDATE ON SALES
FOR EACH ROW 
BEGIN
  :NEW.MODIFIED := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL"."TRIGGER_SALES_MODIFIED" ENABLE;
--------------------------------------------------------
--  DDL for Procedure PROCEDURE_CUSTOMER_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL"."PROCEDURE_CUSTOMER_DELETE" (
 PARAM_CUSTOMER_ID CHAR
) AS
BEGIN
 DELETE FROM CUSTOMERS
 WHERE
  CUSTOMER_ID = PARAM_CUSTOMER_ID;
END PROCEDURE_CUSTOMER_DELETE;

/
--------------------------------------------------------
--  DDL for Procedure PROCEDURE_CUSTOMER_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL"."PROCEDURE_CUSTOMER_UPDATE" (
    PARAM_CUSTOMER_ID CHAR, 
    PARAM_FIRST_NAME VARCHAR2, 
    PARAM_LAST_NAME VARCHAR2, 
    PARAM_ADDRESS VARCHAR2, 
    PARAM_CITY VARCHAR2, 
    PARAM_POSTAL_CODE VARCHAR2, 
    PARAM_EMAIL VARCHAR2, 
    PARAM_PASSWORD VARCHAR2
) AS
BEGIN
    IF LENGTH(PARAM_PASSWORD) BETWEEN 1 AND 10 THEN
        UPDATE CUSTOMERS SET 
            FIRST_NAME = PARAM_FIRST_NAME,
            LAST_NAME = PARAM_LAST_NAME,
            ADDRESS = PARAM_ADDRESS,
            CITY = PARAM_CITY,
            POSTAL_CODE = PARAM_POSTAL_CODE,
            EMAIL = PARAM_EMAIL,
            PASSWORD_HASH = 'hashed_' || PARAM_PASSWORD, -- Replace with actual hashing function
            MODIFIED = CURRENT_TIMESTAMP
        WHERE CUSTOMER_ID = PARAM_CUSTOMER_ID;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Invalid password length');
    END IF;
END PROCEDURE_CUSTOMER_UPDATE;

/
--------------------------------------------------------
--  DDL for Procedure PROCEDURE_PRODUCT_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL"."PROCEDURE_PRODUCT_DELETE" (
 PARAM_PRODUCT_ID CHAR
) AS
BEGIN
 DELETE FROM PRODUCTS
 WHERE
  PRODUCT_ID = PARAM_PRODUCT_ID;
END PROCEDURE_PRODUCT_DELETE;

/
--------------------------------------------------------
--  DDL for Function FUNCTION_CALCULATE_TOTAL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "FINAL"."FUNCTION_CALCULATE_TOTAL" (
 PARAM_PRICE NUMBER,PARAM_QUANTITY NUMBER
) RETURN NUMBER AS
BEGIN
 RETURN PARAM_PRICE * PARAM_QUANTITY;
END FUNCTION_CALCULATE_TOTAL;

/
--------------------------------------------------------
--  DDL for Function FUNCTION_CUSTOMER_SEARCH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "FINAL"."FUNCTION_CUSTOMER_SEARCH" (
 PARAM_LAST_NAME IN VARCHAR2
) RETURN TYPE_CUSTOMER_RECORD_TABLE
 PIPELINED
AS
BEGIN
 FOR C_ROW IN (
  SELECT
   CUSTOMER_ID,FIRST_NAME,LAST_NAME
  FROM
   CUSTOMERS
  WHERE
   UPPER(LAST_NAME) LIKE UPPER('%' || PARAM_LAST_NAME || '%')
 ) LOOP
  PIPE ROW ( TYPE_CUSTOMER_RECORD(C_ROW.CUSTOMER_ID,C_ROW.FIRST_NAME,
  C_ROW.LAST_NAME) );
 END LOOP;
END FUNCTION_CUSTOMER_SEARCH;

/
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "FINAL"."CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."CUSTOMERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."CUSTOMERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."CUSTOMERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."CUSTOMERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."CUSTOMERS" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."CUSTOMERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."CUSTOMERS" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FINAL"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_UK_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "FINAL"."PRODUCTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."PRODUCTS" MODIFY ("PRODUCT_CODE" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FINAL"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_UK_PRODUCT_CODE" UNIQUE ("PRODUCT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "FINAL"."SALES" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL"."SALES" ADD CONSTRAINT "SALES_PK" PRIMARY KEY ("INVOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "FINAL"."SALES" ADD CONSTRAINT "SALES_FK_CUSTOMER_ID" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "FINAL"."CUSTOMERS" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "FINAL"."SALES" ADD CONSTRAINT "SALES_FK_PRODUCT_ID" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "FINAL"."PRODUCTS" ("PRODUCT_ID") ENABLE;
